const userData = {
  githubUsername: "KgFix",
  name: "Kirone Gopaul",
  designation: "Software Developer",
  avatarUrl: "/avatar.png",
  email: "kirgopaul@gmail.com",
  phone: "083 453 7610",
  address: "Durban, South Africa.",
  projects: [
    {
      title: "Financial Intelligence Platform",
      link: "https://github.com/KgFix",
      imgUrl: "/financial-intelligence-platform.png",
    },
    {
      title: "Unity Physics-Based Game",
      link: "https://github.com/KgFix",
      imgUrl: "/unity-game.png",
    },
  ],
  about: {
    title:
      "Proactive final-year Computer Science student bringing hands-on experience across the full software development lifecycle.",
    description: [
      `Proven ability to translate complex requirements into functional applications, demonstrated through projects in both Python (full-stack with automated CI/CD) and C# (complex algorithm development).`,
      `A fast learner eager to secure an entry-level software developer position, ready to adapt to new environments and contribute to building robust, scalable solutions.`,
    ],
    currentProject: "Financial Intelligence Platform",
    currentProjectUrl: "https://github.com/KgFix",
  },
  experience: [
    {
      title: "BSc Computer Science",
      company: "University of KwaZulu-Natal",
      year: "2023 - Present",
      companyLink: "https://ukzn.ac.za/",
      desc: "Awarded Dean's Commendation (2023) and demonstrated high academic achievement in foundational computer science and mathematics. Core Competencies: Strong performance in key development areas including Databases and Programming, Data Structures, Object-Oriented Programming, and Advanced Programming.",
    },
    {
      title: "Private Tutor - Mathematics & Information Technology",
      company: "KG TUITIONS",
      year: "2024",
      companyLink: "",
      desc: "Independently managed client acquisition, scheduling, and billing, demonstrating strong organizational and time-management skills.",
    },
     {
      title: "Seasonal Employee",
      company: "CLICKS GROUP",
      year: "2024",
      companyLink: "https://clicksgroup.co.za/",
      desc: "Managed critical inventory documentation and executed POS transactions, ensuring 99%+ transaction accuracy through meticulous detail verification.",
    },
    {
      title: "Bachelor's Degree Pass",
      company: "Greenbury Secondary",
      year: "2022",
      companyLink: "",
      desc: "Excelled in Information Technology (92%) and Mathematics (89%). Awarded a bursary for Advanced Mathematics and Robotics.",
    },
  ],
  socialLinks: {
    linkedin: "https://linkedin.com/in/kironegopaul",
    github: "https://github.com/KgFix",
  },
  techStack: [
    "Python",
    "C#",
    "Java",
    "C++",
    "SQL",
    "JavaScript",
    "HTML/CSS",
    "HLSL/GLSL",
    "Flask",
    "Plotly Dash",
    "Pandas",
    "Unity",
    "React",
    "Node.js",
    "Git",
    "Docker",
    "CI/CD",
    "LLM APIs",
    "Blender",
    "Ruff",
    "Mypy",
    "VS Code",
    "Visual Studio",
    "IntelliJ",
    "Eclipse",
  ],
};

export default userData;
